### ISSUE TITLE
wrong documentation issue

### ISSUE THREAD

**Issue by vreality64** [naver/egjs-visible#7]
This is documentation of **constructor**
```js
/**
 * @param {HTMLElement|String|jQuery} [element=document] ...
 * @param {Object} options ...
 * @param {String} [options.targetClass="check_visible"] ...
 * @param {Number} [options.expandSize=0] ...
 */
```

It show that jQuery object are allowed as element parameter, but **actually it wasn't.**

If I use jQuery object as an element parameter, it will get an error because there is [code to perform getElementsByClassName on jQuery object](https://github.com/naver/egjs-visible/blob/master/src/Visible.js#L100).

I think constructor needs one more step to unwrapping jQuery object to be saved as `_wrapper`

**Comment by sculove** [comment]
@vreality64 thanks report.
